RheoSolutionClient/Controllers/ProjectController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RheoSolutionClient.Data;
using RheoSolutionClient.Models;
using RheoSolutionClient.ViewModels;

using RheoSolutionClient.Services;
using AutoMapper;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;

namespace RheoSolutionClient.Controllers
{
    [Authorize]
    public class ProjectController : Controller
    {
        private ProjectService _pservice;
        private IMapper _mapper;
        public ProjectController(ProjectService pservice, IMapper mapper)
        {
            _pservice = pservice;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            return View(_pservice.GetAllProjects());
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public  IActionResult Create(ProjectViewModel input)
        {
            if(ModelState.IsValid)
            {
                var result = _mapper.Map<Project>(input);

                _pservice.AddProject(result);
            }

            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            Project toMap = _pservice.GetProjectById(id);
            ProjectViewModel project = _mapper.Map<ProjectViewModel>(toMap);
            return View(project);
        }

        [HttpPost]
        public  IActionResult Edit(ProjectViewModel input)
        {
            if(ModelState.IsValid)
            {
                var result = _mapper.Map<Project>(input);
                _pservice.EditProject(result);
            }

            return RedirectToAction("Index");
        }


        [HttpGet]
        public  IActionResult Delete(int id)
        {
            _pservice.DeleteProject(id);

            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            Project selected = _pservice.GetProjectById(id);
            selected.Measurements = _pservice.GetMeasurementsByProjectId(id);
            return View(_mapper.Map<ProjectViewModel>(selected));
        }

    }
}

RheoSolutionClient/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0" /> -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - Rheology Sim</title>

     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
            asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
            integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    <link rel="stylesheet" href="/css/site.css" asp-append-version="true" />

</head>

<partial name="_CookieConsentPartial" />

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index"><img src="~/images/logo.png" alt="Rheology Sim"/></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Home<span class="sr-only">(current)</span></a>
                        <!-- <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a> -->
                    </li>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Project" asp-action="Index">Projects</a>
                        </li>
                    }

                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="TechnologyStack">Technology Stack</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-controller="Home" asp-action="Contact">Contact</a>
                    </li>
                <partial name="_LoginPartial" />
                </ul>
            </div>
        </div>
    </nav>



    <div class="container body-content">
        @RenderBody()
    </div>

    <footer class="footer">
        <div class="container">
            <span class="text-muted">&copy RheologySim - Grzegorz Orłowicz -</span>
             <a asp-controller="Home" asp-action="Privacy">Privacy Policy</a>
        </div>
    </footer>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous">
    </script>
    <script src="/js/site.min.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>