RheoSolutionClient/Models/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RheoSolutionClient.Models
{

    public class Project
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [MaxLength(50)]
        public string Name { get; set; }
        [MaxLength(250)]
        public string Description { get; set; }
        public DateTime Created { get; set; }
        public DateTime Modified { get; set; }
        public string OwnerId { get; set; }
        //relations
        public List<Measurement> Measurements { get; set; }

    }
}

RheoSolutionClient/ViewModels/ProjectViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using RheoSolutionClient.Models;

namespace RheoSolutionClient.ViewModels
{

    public class ProjectViewModel
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(50)]
        public string Name { get; set; }
        [Required]
        [MaxLength(250)]
        public string Description { get; set; }
        public DateTime Created { get; set; }
        public DateTime Modified { get; set; }
        public string OwnerId { get; set;}
        public List<Measurement> Measurements { get; set; }

    }
}

RheoSolutionClient/Controllers/MeasurementController.cs
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using RheoSolutionClient.ApiModels;
using RheoSolutionClient.Models;
using RheoSolutionClient.Services;
using RheoSolutionClient.ViewModels;

namespace RheoSolutionClient.Controllers
{
    public class MeasurementController : Controller
    {

        private MeasurementService _mservice;
        private IMapper _mapper;
        private  RheoSolutionApiService _apiclient;

        public MeasurementController(MeasurementService mservice, IMapper mapper, RheoSolutionApiService apiclient)
        {
            _apiclient = apiclient;
            _mservice = mservice;
            _mapper = mapper;
        }



        public IActionResult Index(int id)
        {

            Measurement model = _mservice.GetMeasurementById(id);
            RequestModel request = new RequestModel(){
                Bob = model.Bob,
                Rotor = model.Rotor,
                Spring = model.Spring,
                Angle = model.SpeedAngle.Values.ToArray(),
                Rate = model.SpeedAngle.Keys.ToArray()
            };

            RheologyResponseModel rheology =  _apiclient.GetRheologyAsync(request).Result;
            List<RheoModelResponseModel> models = _apiclient.GetAllRheoModelsAsync(request).Result;

            RheoTotalViewModel rheoTotal = new RheoTotalViewModel(){
                Models = models,
                Rheology = rheology,
                Bob = request.Bob,
                Rotor = request.Rotor,
                Spring = request.Spring,
            };

            MeasurementViewModel result = _mapper.Map<MeasurementViewModel>(model);
            result.Data = rheoTotal;



            return View(result);
        }

        [HttpGet]
        public IActionResult Create()
        {
            int[] rate = new int[12]{1,2,3,6,10,20,30,60,100,200,300,600};
            ViewBag.rate = rate;
            return View();
        }
        [HttpPost]
        public IActionResult Create(MeasurementInputVM model, int id)
        {
            MeasurementViewModel measurement = model.Measurement;
            measurement.ProjectId = id;

            Measurement result = _mapper.Map<Measurement>(measurement);
            result.SpeedAngle = new Dictionary<int,double>();

            //filter selected
            int i = 0;
            foreach( var el in model.Measurement.SpeedAngle)
            {
                if(model.Selected[i])
                {
                    result.SpeedAngle.Add(el.Key,el.Value);
                }
                i++;
            }

            int mesId = _mservice.AddMeasurement(result);

            return RedirectToAction("index", new { Id = mesId} );
        }
    }
}

RheoSolutionClient/Controllers/ProjectController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RheoSolutionClient.Data;
using RheoSolutionClient.Models;
using RheoSolutionClient.ViewModels;

using RheoSolutionClient.Services;
using AutoMapper;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;

namespace RheoSolutionClient.Controllers
{
    [Authorize]
    public class ProjectController : Controller
    {
        private ProjectService _pservice;
        private IMapper _mapper;
        public ProjectController(ProjectService pservice, IMapper mapper)
        {
            _pservice = pservice;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            return View(_pservice.GetAllProjects());
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public  IActionResult Create(ProjectViewModel input)
        {
            if(ModelState.IsValid)
            {
                var result = _mapper.Map<Project>(input);

                _pservice.AddProject(result);
            }

            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            Project toMap = _pservice.GetProjectById(id);
            ProjectViewModel project = _mapper.Map<ProjectViewModel>(toMap);
            return View(project);
        }

        [HttpPost]
        public  IActionResult Edit(ProjectViewModel input)
        {
            if(ModelState.IsValid)
            {
                var result = _mapper.Map<Project>(input);
                _pservice.EditProject(result);
            }

            return RedirectToAction("Index");
        }


        [HttpGet]
        public  IActionResult Delete(int id)
        {
            _pservice.DeleteProject(id);

            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            Project selected = _pservice.GetProjectById(id);
            selected.Measurements = _pservice.GetMeasurementsByProjectId(id);
            return View(_mapper.Map<ProjectViewModel>(selected));
        }

    }
}

RheoSolutionClient/Views/Project/Create.cshtml
@using RheoSolutionClient.ViewModels
@model ProjectViewModel

@{
    ViewData["Title"] = "Project";
}

<div class="container">
    <h3>Create new project</h3>
    <br/>

    <form method="post" asp-controller="Project" asp-action="Create">
    <div asp-validation-summary="All" class="text-danger"></div>

       <div class="form-group">
           <label>Name</label>
           <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
       </div>
       <div class="form-group">
           <label>Description</label>
           <input asp-for="Description" class="form-control"/>
            <span asp-validation-for="Description" class="text-danger"></span>

       </div>


       <input type="submit" class = "btn btn-outline-secondary" name="save" value="Save"/>
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

RheoSolutionClient/Views/Project/Details.cshtml
@using RheoSolutionClient.ViewModels
@model ProjectViewModel

@{
    ViewData["Title"] = "Project";
}

<div class="container">
    <br/>
    <h3>Project: @Model.Name</h3>
    <br/>
    <div class="card">
        <div class="card-header">
            <h4>List of measurements</h4>
        </div>
        <!-- /.card-heading -->
        <div class="card-body table-responsive">
            <table class ="table table-hover table-striped">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Created</th>
                        <th>Modified</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var mes in Model.Measurements)
                    {
                        <tr>
                            <td>@mes.Id</td>
                            <td><a class= "btn btn-outline-secondary btn-block" asp-controller="Measurement" asp-action="Index" asp-route-id="@mes.Id">@mes.Name</a></td>
                            <td>@mes.Description</td>
                            <td>@mes.Created.ToShortDateString()</td>
                            <td>@mes.Modified.ToShortDateString()</td>
                        </tr>
                    }
                </tbody>
            </table>
            <a asp-controller="Measurement" asp-action="Create" class="btn btn-outline-secondary" asp-route-id="@Model.Id">New measurement</a>
        </div>
        <!-- card body -->
    </div>
    <!-- card -->
</div>

RheoSolutionClient/Views/Project/Edit.cshtml
@using RheoSolutionClient.ViewModels
@model ProjectViewModel

@{
    ViewData["Title"] = "Project";
}

<div class="container">
    <h3>Edit project</h3>
    <br/>
    <form method="post" asp-controller="Project" asp-action="Edit">
    <div asp-validation-summary="All" class="text-danger"></div>

       <div class="form-group">
           <label>Name</label>
           <input asp-for="@Model.Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>

       </div>
       <div class="form-group">
           <label>Description</label>
           <input asp-for="@Model.Description" class="form-control"/>
            <span asp-validation-for="Description" class="text-danger"></span>
       </div>


       <input type="submit" class = "btn btn-outline-secondary" name="save" value="Save"/>
   </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

RheoSolutionClient/Views/Project/Index.cshtml
@using RheoSolutionClient.Models
@model List<Project>

@{
    ViewData["Title"] = "Project";
}

<div class="container">
    <h3>Projects</h2>
    <br/>

    <div class="card">
        <div class="card-header">
            <h4>List of projects</h4>
        </div>
        <!-- /.card-heading -->
        <div class="card-body table-responsive">
            <table class ="table table-hover table-striped">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Created</th>
                        <th>Modified</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(var project in Model)
                    {
                        <tr>
                            <td>@project.Id</td>
                            <td><a class= "btn btn-outline-secondary btn-block" asp-controller="Project" asp-action="Details" asp-route-id="@project.Id">@project.Name</a></td>
                            <td>@project.Description</td>
                            <td>@project.Created.ToShortDateString()</td>
                            <td>@project.Modified.ToShortDateString()</td>
                            <td><a class= "btn btn-outline-secondary" asp-controller="Project" asp-action="Edit" asp-route-id="@project.Id">Edit</a></td>
                            <td><a class= "btn btn-outline-secondary" asp-controller="Project" asp-action="Delete" asp-route-id="@project.Id" onclick="return confirm('Are you sure?')">Delete</a></td>

                        </tr>
                    }
                </tbody>
            </table>
            <a asp-controller="Project" asp-action="Create" class="btn btn-outline-secondary">Create new project</a>
        </div>
        <!-- card body -->
    </div>
    <!-- card -->
</div>